2025-05-16 22:35:50 - capsola_api - ERROR - Ошибка при решении SmartCaptcha: 404 Client Error: Not found for url: https://ext.captcha.yandex.net/image?key=00AfGWqOb5RCMUJDOVNvkylSd0423a72&data=img
Traceback (most recent call last):
  File "C:\Users\priva\Desktop\Zapros2\capsola.py", line 84, in solve_smart_captcha
    img_response.raise_for_status()
  File "C:\Users\priva\Desktop\Zapros2\.venv1\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not found for url: https://ext.captcha.yandex.net/image?key=00AfGWqOb5RCMUJDOVNvkylSd0423a72&data=img
